#
###################################
# Site wide configuration
####################################
#
title: Leonids
email: 
description: A simple and awesome blog theme powered by jekyll.
# the base hostname & protocol for your site
# If your project is placed in https://github.com/yourname/yourname.github.io at master branch
# Then, the 'url' is: http://yourname.github.io
# If your project is placed in another repository as a gh-pages branch, like: https://github.com/yourname/projectname
# Then, the 'url' is: http://yourname.github.io/projectname
url: 

#
###################################
# Jekyll configuration
####################################
#
markdown:    kramdown
highlighter:  pygments
excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Bomao Huang
  avatar: avatar.jpg
  job: "iOS Developer"
  bio: "I am Bomao Huang, an iOS Developer. I love anything about Internet technologies, especially on mobile. Take a look of my blogger posts, and hope we share soenthing useful."
  email: williamwong89@gmail.com
  disqus-shortname:
  twitter: william_Wong89
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: biscat
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: bomao-huang-94448626
  xing: #username
  instagram: williamwong89
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
