#
###################################
# Site wide configuration
####################################
#
title:       "Bomao's blog"
description: 'An iOS developer that loves anythings on Internet Technologies, especially on Mobile. Work for ByteDance in Shenzhen China'
url:         https://biscat.tech/

#
###################################
# Jekyll configuration
####################################
#
timezone:          China/Beijing
markdown:          kramdown
highlighter:        pygments
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap

- jekyll-feed

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Bomao
  avatar: avatar.jpg
  job:  "iOS Developer"
  bio:  "An iOS developer that loves anythings on Internet Technologies, especially on Mobile. Work for Fleetmatics in Dublin Ireland."
  email:  williamwong89@gmail.com
  disqus-shortname: 
  twitter: bomaohuang #username
  facebook: #username
  google:
    plus: #username
    analytics: #UA-62251910-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: biscat
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
